djangoapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('people.urls')),
]

people/urls.py
from django.conf.urls import url

from . import views

app_name = 'people'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/$', views.ListView.as_view(), name='list'),
    url(r'^add/$', views.AddView.as_view(), name='add'),
]

people/models.py
from __future__ import unicode_literals

from django.db import models

class People(models.Model):
    name = models.CharField(max_length=200, blank=False)
    email = models.EmailField(max_length=200, blank=False, unique=True)

    def __str__(self):
        return self.name

people/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import View
from django.views import generic
from django.views.generic.edit import CreateView

from .models import People

class IndexView(View):
    template_name = 'people/index.html'

    def get(self, request):
        return render(request, self.template_name)

class ListView(generic.ListView):
    template_name = 'people/list.html'
    context_object_name = 'people_list'
    
    def get_queryset(self):
        return People.objects.order_by('name')

class AddView(CreateView):
    model = People
    fields = ['name', 'email']
    template_name = 'people/add.html'
    success_url = reverse_lazy('people:add')

people/templates/people/add.html
{% extends "people/base.html" %}

{% block title %}New Person{% endblock %}

{% block content %}
<h1>New person</h1>

<form action="{% url 'people:add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <input type="submit" value="Add">
    </p>
</form>

<p>
    [<a href="{% url 'people:list' %}">Return to 'List of people'</a>]
</p>
{% endblock %}

people/templates/people/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'people/style.css' %}" />
    <title>{% block title %}A Django App{% endblock %}</title>
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

people/templates/people/index.html
{% extends "people/base.html" %}

{% block content %}
<ul>
    <li><a href="{% url 'people:list' %}">List of people</a></li>
    <li><a href="{% url 'people:add' %}">Add people</a></li>
</ul>
{% endblock %}

people/templates/people/list.html
{% extends "people/base.html" %}

{% block title %}List{% endblock %}

{% block content %}
{% if people_list %}
    <ul>
    {% for people in people_list %}
        <li>{{ people.name }} - {{ people.email }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No people are available.</p>
{% endif %}
<p>
    [<a href="{% url 'people:add' %}">Add people</a>]
</p>
{% endblock %}